//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace moduloMonitorWCF.IndexadorServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IndexadorServiceReference.IIndexadorWS")]
    public interface IIndexadorWS {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIndexadorWS/indexarLink", ReplyAction="http://tempuri.org/IIndexadorWS/indexarLinkResponse")]
        string indexarLink(int identificador, bool novoAgente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIndexadorWS/indexarLink", ReplyAction="http://tempuri.org/IIndexadorWS/indexarLinkResponse")]
        System.Threading.Tasks.Task<string> indexarLinkAsync(int identificador, bool novoAgente);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IIndexadorWSChannel : moduloMonitorWCF.IndexadorServiceReference.IIndexadorWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IndexadorWSClient : System.ServiceModel.ClientBase<moduloMonitorWCF.IndexadorServiceReference.IIndexadorWS>, moduloMonitorWCF.IndexadorServiceReference.IIndexadorWS {
        
        public IndexadorWSClient() {
        }
        
        public IndexadorWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IndexadorWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IndexadorWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IndexadorWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string indexarLink(int identificador, bool novoAgente) {
            return base.Channel.indexarLink(identificador, novoAgente);
        }
        
        public System.Threading.Tasks.Task<string> indexarLinkAsync(int identificador, bool novoAgente) {
            return base.Channel.indexarLinkAsync(identificador, novoAgente);
        }
    }
}
