//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.RastreadorServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RastreadorServiceReference.IRastreadorWS")]
    public interface IRastreadorWS {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRastreadorWS/rastrear", ReplyAction="http://tempuri.org/IRastreadorWS/rastrearResponse")]
        void rastrear(int nivel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRastreadorWS/rastrear", ReplyAction="http://tempuri.org/IRastreadorWS/rastrearResponse")]
        System.Threading.Tasks.Task rastrearAsync(int nivel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRastreadorWS/rastrearLink", ReplyAction="http://tempuri.org/IRastreadorWS/rastrearLinkResponse")]
        void rastrearLink(string link, int nivel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRastreadorWS/rastrearLink", ReplyAction="http://tempuri.org/IRastreadorWS/rastrearLinkResponse")]
        System.Threading.Tasks.Task rastrearLinkAsync(string link, int nivel);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRastreadorWSChannel : WebApplication.RastreadorServiceReference.IRastreadorWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RastreadorWSClient : System.ServiceModel.ClientBase<WebApplication.RastreadorServiceReference.IRastreadorWS>, WebApplication.RastreadorServiceReference.IRastreadorWS {
        
        public RastreadorWSClient() {
        }
        
        public RastreadorWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RastreadorWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RastreadorWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RastreadorWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void rastrear(int nivel) {
            base.Channel.rastrear(nivel);
        }
        
        public System.Threading.Tasks.Task rastrearAsync(int nivel) {
            return base.Channel.rastrearAsync(nivel);
        }
        
        public void rastrearLink(string link, int nivel) {
            base.Channel.rastrearLink(link, nivel);
        }
        
        public System.Threading.Tasks.Task rastrearLinkAsync(string link, int nivel) {
            return base.Channel.rastrearLinkAsync(link, nivel);
        }
    }
}
