//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacaoNotificacaoTeste.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.INotificadorService")]
    public interface INotificadorService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotificadorService/notificarAtualizacao", ReplyAction="http://tempuri.org/INotificadorService/notificarAtualizacaoResponse")]
        bool notificarAtualizacao();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotificadorService/notificarAtualizacao", ReplyAction="http://tempuri.org/INotificadorService/notificarAtualizacaoResponse")]
        System.Threading.Tasks.Task<bool> notificarAtualizacaoAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INotificadorServiceChannel : AplicacaoNotificacaoTeste.ServiceReference1.INotificadorService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NotificadorServiceClient : System.ServiceModel.ClientBase<AplicacaoNotificacaoTeste.ServiceReference1.INotificadorService>, AplicacaoNotificacaoTeste.ServiceReference1.INotificadorService {
        
        public NotificadorServiceClient() {
        }
        
        public NotificadorServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NotificadorServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NotificadorServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NotificadorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool notificarAtualizacao() {
            return base.Channel.notificarAtualizacao();
        }
        
        public System.Threading.Tasks.Task<bool> notificarAtualizacaoAsync() {
            return base.Channel.notificarAtualizacaoAsync();
        }
    }
}
