//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace acn_trabalho_final.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("acn_trabalho_final.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 948:ABIGAIL RODRIGUES
        ///960:ACKIE MCLEAN
        ///1995:ADÃO DA COSTA RAVAZI
        ///1886:ADÃO DE ASSIS BRASIL
        ///1275:ADÃO JOBIM
        ///1727:ADELINO BRASILIENSA
        ///146:ADELMO OLIVEIRA
        ///718:ADIL JOBIM BRASIL
        ///1160:ADOLFO PFEIFER
        ///170:ADONIAS FILHO
        ///836:ADRIANA DE ANDRADE SOARES
        ///1594:ADRIANA PELLEGRIN VIEIRA
        ///910:ADRIANA QUERINO CEZAR DE ANDRADE
        ///1541:ADRIANA QUERINO SOUZA DOS SANTOS
        ///1906:ADRIANO BRASILIENSE MARCANTÔNIO
        ///2063:ADRIANO MENDONÇA SOUZA
        ///1615:ADROALDO COELHO LEAL
        ///1719:ADYL DE ASSIS BRASIL
        ///1759:AFFONSO MANTA
        ///490:AFONSO [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pessoas {
            get {
                return ResourceManager.GetString("pessoas", resourceCulture);
            }
        }
    }
}
