//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace moduloMonitorWCF.MonitorServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MonitorServiceReference.IMonitorService")]
    public interface IMonitorService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitorService/iniciarMonitoramento", ReplyAction="http://tempuri.org/IMonitorService/iniciarMonitoramentoResponse")]
        string iniciarMonitoramento();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitorService/iniciarMonitoramento", ReplyAction="http://tempuri.org/IMonitorService/iniciarMonitoramentoResponse")]
        System.Threading.Tasks.Task<string> iniciarMonitoramentoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitorService/pararMonitoramento", ReplyAction="http://tempuri.org/IMonitorService/pararMonitoramentoResponse")]
        string pararMonitoramento();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitorService/pararMonitoramento", ReplyAction="http://tempuri.org/IMonitorService/pararMonitoramentoResponse")]
        System.Threading.Tasks.Task<string> pararMonitoramentoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitorService/inserirFila", ReplyAction="http://tempuri.org/IMonitorService/inserirFilaResponse")]
        void inserirFila(string mensagem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitorService/inserirFila", ReplyAction="http://tempuri.org/IMonitorService/inserirFilaResponse")]
        System.Threading.Tasks.Task inserirFilaAsync(string mensagem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitorService/lerProximaMensagem", ReplyAction="http://tempuri.org/IMonitorService/lerProximaMensagemResponse")]
        string lerProximaMensagem();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitorService/lerProximaMensagem", ReplyAction="http://tempuri.org/IMonitorService/lerProximaMensagemResponse")]
        System.Threading.Tasks.Task<string> lerProximaMensagemAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitorService/listarMensagensFila", ReplyAction="http://tempuri.org/IMonitorService/listarMensagensFilaResponse")]
        string listarMensagensFila();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitorService/listarMensagensFila", ReplyAction="http://tempuri.org/IMonitorService/listarMensagensFilaResponse")]
        System.Threading.Tasks.Task<string> listarMensagensFilaAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMonitorServiceChannel : moduloMonitorWCF.MonitorServiceReference.IMonitorService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MonitorServiceClient : System.ServiceModel.ClientBase<moduloMonitorWCF.MonitorServiceReference.IMonitorService>, moduloMonitorWCF.MonitorServiceReference.IMonitorService {
        
        public MonitorServiceClient() {
        }
        
        public MonitorServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MonitorServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MonitorServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MonitorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string iniciarMonitoramento() {
            return base.Channel.iniciarMonitoramento();
        }
        
        public System.Threading.Tasks.Task<string> iniciarMonitoramentoAsync() {
            return base.Channel.iniciarMonitoramentoAsync();
        }
        
        public string pararMonitoramento() {
            return base.Channel.pararMonitoramento();
        }
        
        public System.Threading.Tasks.Task<string> pararMonitoramentoAsync() {
            return base.Channel.pararMonitoramentoAsync();
        }
        
        public void inserirFila(string mensagem) {
            base.Channel.inserirFila(mensagem);
        }
        
        public System.Threading.Tasks.Task inserirFilaAsync(string mensagem) {
            return base.Channel.inserirFilaAsync(mensagem);
        }
        
        public string lerProximaMensagem() {
            return base.Channel.lerProximaMensagem();
        }
        
        public System.Threading.Tasks.Task<string> lerProximaMensagemAsync() {
            return base.Channel.lerProximaMensagemAsync();
        }
        
        public string listarMensagensFila() {
            return base.Channel.listarMensagensFila();
        }
        
        public System.Threading.Tasks.Task<string> listarMensagensFilaAsync() {
            return base.Channel.listarMensagensFilaAsync();
        }
    }
}
