
package puc.pf.portal.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import _106._0._168._192._8080.jaxws.dominio.excecaocapturada.ExcecaoCapturada;
import _106._0._168._192._8080.jaxws.dominio.funcionario.Funcionario;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "iserviceportal", targetNamespace = "http://192.168.0.106:8080/jaxws")
@XmlSeeAlso({
    _106._0._168._192._8080.jaxws.dominio.funcionario.ObjectFactory.class,
    _106._0._168._192._8080.jaxws.dominio.excecaocapturada.ObjectFactory.class,
    _106._0._168._192._8080.jaxws.dominio.basebean.ObjectFactory.class,
    _106._0._168._192._8080.jaxws.ObjectFactory.class
})
public interface Iserviceportal {


    /**
     * 
     * @param arg0
     * @return
     *     returns _106._0._168._192._8080.jaxws.dominio.excecaocapturada.ExcecaoCapturada
     */
    @WebMethod(action = "http://192.168.0.106:8080/jaxws/consultarExcecao")
    @WebResult(name = "ExcecaoCapturada", targetNamespace = "http://192.168.0.106:8080/jaxws/dominio/excecaocapturada")
    @RequestWrapper(localName = "consultarExcecao", targetNamespace = "http://192.168.0.106:8080/jaxws", className = "_106._0._168._192._8080.jaxws.ConsultarExcecao")
    @ResponseWrapper(localName = "consultarExcecaoResponse", targetNamespace = "http://192.168.0.106:8080/jaxws", className = "_106._0._168._192._8080.jaxws.ConsultarExcecaoResponse")
    public ExcecaoCapturada consultarExcecao(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @return
     *     returns java.util.List<_106._0._168._192._8080.jaxws.dominio.excecaocapturada.ExcecaoCapturada>
     */
    @WebMethod(action = "http://192.168.0.106:8080/jaxws/consultarListaExcecao")
    @WebResult(name = "ListaExcecaoCapturada", targetNamespace = "http://192.168.0.106:8080/jaxws/dominio/excecaocapturada")
    @RequestWrapper(localName = "consultarListaExcecao", targetNamespace = "http://192.168.0.106:8080/jaxws", className = "_106._0._168._192._8080.jaxws.ConsultarListaExcecao")
    @ResponseWrapper(localName = "consultarListaExcecaoResponse", targetNamespace = "http://192.168.0.106:8080/jaxws", className = "_106._0._168._192._8080.jaxws.ConsultarListaExcecaoResponse")
    public List<ExcecaoCapturada> consultarListaExcecao();

    /**
     * 
     * @param arg0
     * @return
     *     returns _106._0._168._192._8080.jaxws.dominio.funcionario.Funcionario
     */
    @WebMethod(action = "http://192.168.0.106:8080/jaxws/consultarFuncionario")
    @WebResult(name = "Funcionario", targetNamespace = "http://192.168.0.106:8080/jaxws/dominio/funcionario")
    @RequestWrapper(localName = "consultarFuncionario", targetNamespace = "http://192.168.0.106:8080/jaxws", className = "_106._0._168._192._8080.jaxws.ConsultarFuncionario")
    @ResponseWrapper(localName = "consultarFuncionarioResponse", targetNamespace = "http://192.168.0.106:8080/jaxws", className = "_106._0._168._192._8080.jaxws.ConsultarFuncionarioResponse")
    public Funcionario consultarFuncionario(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @return
     *     returns java.util.List<_106._0._168._192._8080.jaxws.dominio.funcionario.Funcionario>
     */
    @WebMethod(action = "http://192.168.0.106:8080/jaxws/consultarListaFuncionario")
    @WebResult(name = "ListaFuncionario", targetNamespace = "http://192.168.0.106:8080/jaxws/dominio/funcionario")
    @RequestWrapper(localName = "consultarListaFuncionario", targetNamespace = "http://192.168.0.106:8080/jaxws", className = "_106._0._168._192._8080.jaxws.ConsultarListaFuncionario")
    @ResponseWrapper(localName = "consultarListaFuncionarioResponse", targetNamespace = "http://192.168.0.106:8080/jaxws", className = "_106._0._168._192._8080.jaxws.ConsultarListaFuncionarioResponse")
    public List<Funcionario> consultarListaFuncionario();

}
