package magento;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-12-02T22:19:59.161-02:00
 * Generated source version: 2.7.7
 * 
 */
@WebService(targetNamespace = "urn:Magento", name = "Mage_Api_Model_Server_Wsi_HandlerPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface MageApiModelServerWsiHandlerPortType {

    /**
     * Get total prices for shopping cart
     */
    @WebResult(name = "shoppingCartTotalsResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public ShoppingCartTotalsResponseParam shoppingCartTotals(
        @WebParam(partName = "parameters", name = "shoppingCartTotalsRequestParam", targetNamespace = "urn:Magento")
        ShoppingCartTotalsRequestParam parameters
    );

    /**
     * Create new shipment for order
     */
    @WebResult(name = "salesOrderShipmentCreateResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public SalesOrderShipmentCreateResponseParam salesOrderShipmentCreate(
        @WebParam(partName = "parameters", name = "salesOrderShipmentCreateRequestParam", targetNamespace = "urn:Magento")
        SalesOrderShipmentCreateRequestParam parameters
    );

    /**
     * Assign product link
     */
    @WebResult(name = "catalogProductLinkAssignResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductLinkAssignResponseParam catalogProductLinkAssign(
        @WebParam(partName = "parameters", name = "catalogProductLinkAssignRequestParam", targetNamespace = "urn:Magento")
        CatalogProductLinkAssignRequestParam parameters
    );

    /**
     * Cancel order
     */
    @WebResult(name = "salesOrderCancelResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public SalesOrderCancelResponseParam salesOrderCancel(
        @WebParam(partName = "parameters", name = "salesOrderCancelRequestParam", targetNamespace = "urn:Magento")
        SalesOrderCancelRequestParam parameters
    );

    /**
     * Retrieve customers
     */
    @WebResult(name = "customerCustomerListResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CustomerCustomerListResponseParam customerCustomerList(
        @WebParam(partName = "parameters", name = "customerCustomerListRequestParam", targetNamespace = "urn:Magento")
        CustomerCustomerListRequestParam parameters
    );

    /**
     * Retrieve category attributes
     */
    @WebResult(name = "catalogCategoryAttributeListResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogCategoryAttributeListResponseParam catalogCategoryAttributeList(
        @WebParam(partName = "parameters", name = "catalogCategoryAttributeListRequestParam", targetNamespace = "urn:Magento")
        CatalogCategoryAttributeListRequestParam parameters
    );

    /**
     * Create an order from shopping cart
     */
    @WebResult(name = "shoppingCartOrderResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public ShoppingCartOrderResponseParam shoppingCartOrder(
        @WebParam(partName = "parameters", name = "shoppingCartOrderRequestParam", targetNamespace = "urn:Magento")
        ShoppingCartOrderRequestParam parameters
    );

    /**
     * Multi update product stock data
     */
    @WebResult(name = "catalogInventoryStockItemMultiUpdateResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogInventoryStockItemMultiUpdateResponseParam catalogInventoryStockItemMultiUpdate(
        @WebParam(partName = "parameters", name = "catalogInventoryStockItemMultiUpdateRequestParam", targetNamespace = "urn:Magento")
        CatalogInventoryStockItemMultiUpdateRequestParam parameters
    );

    /**
     * Redeem gift card amount
     */
    @WebResult(name = "shoppingCartGiftcardRemoveResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public ShoppingCartGiftcardRemoveResponseParam shoppingCartGiftcardRemove(
        @WebParam(partName = "parameters", name = "shoppingCartGiftcardRemoveRequestParam", targetNamespace = "urn:Magento")
        ShoppingCartGiftcardRemoveRequestParam parameters
    );

    /**
     * Remove product tag
     */
    @WebResult(name = "catalogProductTagRemoveResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductTagRemoveResponseParam catalogProductTagRemove(
        @WebParam(partName = "parameters", name = "catalogProductTagRemoveRequestParam", targetNamespace = "urn:Magento")
        CatalogProductTagRemoveRequestParam parameters
    );

    /**
     * Set amount from customer store credit into shopping cart (quote)
     */
    @WebResult(name = "shoppingCartCustomerbalanceSetAmountResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public ShoppingCartCustomerbalanceSetAmountResponseParam shoppingCartCustomerbalanceSetAmount(
        @WebParam(partName = "parameters", name = "shoppingCartCustomerbalanceSetAmountRequestParam", targetNamespace = "urn:Magento")
        ShoppingCartCustomerbalanceSetAmountRequestParam parameters
    );

    /**
     * Remove product assignment from category
     */
    @WebResult(name = "catalogCategoryRemoveProductResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogCategoryRemoveProductResponseParam catalogCategoryRemoveProduct(
        @WebParam(partName = "parameters", name = "catalogCategoryRemoveProductRequestParam", targetNamespace = "urn:Magento")
        CatalogCategoryRemoveProductRequestParam parameters
    );

    /**
     * Retrieve attribute list
     */
    @WebResult(name = "catalogProductAttributeListResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductAttributeListResponseParam catalogProductAttributeList(
        @WebParam(partName = "parameters", name = "catalogProductAttributeListRequestParam", targetNamespace = "urn:Magento")
        CatalogProductAttributeListRequestParam parameters
    );

    /**
     * Retrieve information about shopping cart
     */
    @WebResult(name = "shoppingCartInfoResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public ShoppingCartInfoResponseParam shoppingCartInfo(
        @WebParam(partName = "parameters", name = "shoppingCartInfoRequestParam", targetNamespace = "urn:Magento")
        ShoppingCartInfoRequestParam parameters
    );

    /**
     * Retrieve list of creditmemos by filters
     */
    @WebResult(name = "salesOrderCreditmemoListResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public SalesOrderCreditmemoListResponseParam salesOrderCreditmemoList(
        @WebParam(partName = "parameters", name = "salesOrderCreditmemoListRequestParam", targetNamespace = "urn:Magento")
        SalesOrderCreditmemoListRequestParam parameters
    );

    /**
     * Retrieve products list by filters
     */
    @WebResult(name = "catalogProductListResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductListResponseParam catalogProductList(
        @WebParam(partName = "parameters", name = "catalogProductListRequestParam", targetNamespace = "urn:Magento")
        CatalogProductListRequestParam parameters
    );

    /**
     * Store view info
     */
    @WebResult(name = "storeInfoResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public StoreInfoResponseParam storeInfo(
        @WebParam(partName = "parameters", name = "storeInfoRequestParam", targetNamespace = "urn:Magento")
        StoreInfoRequestParam parameters
    );

    /**
     * Retrieve product image types
     */
    @WebResult(name = "catalogProductAttributeMediaTypesResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductAttributeMediaTypesResponseParam catalogProductAttributeMediaTypes(
        @WebParam(partName = "parameters", name = "catalogProductAttributeMediaTypesRequestParam", targetNamespace = "urn:Magento")
        CatalogProductAttributeMediaTypesRequestParam parameters
    );

    /**
     * List of resource faults
     */
    @WebResult(name = "resourceFaultsResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public ResourceFaultsResponseParam resourceFaults(
        @WebParam(partName = "parameters", name = "resourceFaultsParam", targetNamespace = "urn:Magento")
        ResourceFaultsParam parameters
    );

    /**
     * Retrieve shipment information
     */
    @WebResult(name = "salesOrderShipmentInfoResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public SalesOrderShipmentInfoResponseParam salesOrderShipmentInfo(
        @WebParam(partName = "parameters", name = "salesOrderShipmentInfoRequestParam", targetNamespace = "urn:Magento")
        SalesOrderShipmentInfoRequestParam parameters
    );

    /**
     * Retrieve invoice information
     */
    @WebResult(name = "salesOrderInvoiceInfoResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public SalesOrderInvoiceInfoResponseParam salesOrderInvoiceInfo(
        @WebParam(partName = "parameters", name = "salesOrderInvoiceInfoRequestParam", targetNamespace = "urn:Magento")
        SalesOrderInvoiceInfoRequestParam parameters
    );

    /**
     * Retrieve product types
     */
    @WebResult(name = "catalogProductTypeListResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductTypeListResponseParam catalogProductTypeList(
        @WebParam(partName = "parameters", name = "catalogProductTypeListRequestParam", targetNamespace = "urn:Magento")
        CatalogProductTypeListRequestParam parameters
    );

    /**
     * Delete category
     */
    @WebResult(name = "catalogCategoryDeleteResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogCategoryDeleteResponseParam catalogCategoryDelete(
        @WebParam(partName = "parameters", name = "catalogCategoryDeleteRequestParam", targetNamespace = "urn:Magento")
        CatalogCategoryDeleteRequestParam parameters
    );

    /**
     * Delete customer address
     */
    @WebResult(name = "customerAddressDeleteResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CustomerAddressDeleteResponseParam customerAddressDelete(
        @WebParam(partName = "parameters", name = "customerAddressDeleteRequestParam", targetNamespace = "urn:Magento")
        CustomerAddressDeleteRequestParam parameters
    );

    /**
     * Set/Get current store view
     */
    @WebResult(name = "catalogProductAttributeCurrentStoreResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductAttributeCurrentStoreResponseParam catalogProductAttributeCurrentStore(
        @WebParam(partName = "parameters", name = "catalogProductAttributeCurrentStoreRequestParam", targetNamespace = "urn:Magento")
        CatalogProductAttributeCurrentStoreRequestParam parameters
    );

    /**
     * Retrieve list of allowed carriers for order
     */
    @WebResult(name = "salesOrderShipmentGetCarriersResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public SalesOrderShipmentGetCarriersResponseParam salesOrderShipmentGetCarriers(
        @WebParam(partName = "parameters", name = "salesOrderShipmentGetCarriersRequestParam", targetNamespace = "urn:Magento")
        SalesOrderShipmentGetCarriersRequestParam parameters
    );

    /**
     * Set/Get current store view
     */
    @WebResult(name = "catalogCategoryAttributeCurrentStoreResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogCategoryAttributeCurrentStoreResponseParam catalogCategoryAttributeCurrentStore(
        @WebParam(partName = "parameters", name = "catalogCategoryAttributeCurrentStoreRequestParam", targetNamespace = "urn:Magento")
        CatalogCategoryAttributeCurrentStoreRequestParam parameters
    );

    /**
     * Create new category and return its id.
     */
    @WebResult(name = "catalogCategoryCreateResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogCategoryCreateResponseParam catalogCategoryCreate(
        @WebParam(partName = "parameters", name = "catalogCategoryCreateRequestParam", targetNamespace = "urn:Magento")
        CatalogCategoryCreateRequestParam parameters
    );

    /**
     * Set a gift message to the cart
     */
    @WebResult(name = "giftMessageForQuoteResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public GiftMessageForQuoteResponseParam giftMessageSetForQuote(
        @WebParam(partName = "parameters", name = "giftMessageForQuoteRequestParam", targetNamespace = "urn:Magento")
        GiftMessageForQuoteRequestParam parameters
    );

    /**
     * Update product image
     */
    @WebResult(name = "catalogProductAttributeMediaUpdateResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductAttributeMediaUpdateResponseParam catalogProductAttributeMediaUpdate(
        @WebParam(partName = "parameters", name = "catalogProductAttributeMediaUpdateRequestParam", targetNamespace = "urn:Magento")
        CatalogProductAttributeMediaUpdateRequestParam parameters
    );

    /**
     * Retrieve list of orders by filters
     */
    @WebResult(name = "salesOrderListResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public SalesOrderListResponseParam salesOrderList(
        @WebParam(partName = "parameters", name = "salesOrderListRequestParam", targetNamespace = "urn:Magento")
        SalesOrderListRequestParam parameters
    );

    /**
     * Update assigned product
     */
    @WebResult(name = "catalogCategoryUpdateProductResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogCategoryUpdateProductResponseParam catalogCategoryUpdateProduct(
        @WebParam(partName = "parameters", name = "catalogCategoryUpdateProductRequestParam", targetNamespace = "urn:Magento")
        CatalogCategoryUpdateProductRequestParam parameters
    );

    /**
     * Remove tracking number
     */
    @WebResult(name = "salesOrderShipmentRemoveTrackResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public SalesOrderShipmentRemoveTrackResponseParam salesOrderShipmentRemoveTrack(
        @WebParam(partName = "parameters", name = "salesOrderShipmentRemoveTrackRequestParam", targetNamespace = "urn:Magento")
        SalesOrderShipmentRemoveTrackRequestParam parameters
    );

    /**
     * Retrieve hierarchical tree of categories.
     */
    @WebResult(name = "catalogCategoryTreeResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogCategoryTreeResponseParam catalogCategoryTree(
        @WebParam(partName = "parameters", name = "catalogCategoryTreeRequestParam", targetNamespace = "urn:Magento")
        CatalogCategoryTreeRequestParam parameters
    );

    /**
     * Retrieve attribute options
     */
    @WebResult(name = "catalogCategoryAttributeOptionsResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogCategoryAttributeOptionsResponseParam catalogCategoryAttributeOptions(
        @WebParam(partName = "parameters", name = "catalogCategoryAttributeOptionsRequestParam", targetNamespace = "urn:Magento")
        CatalogCategoryAttributeOptionsRequestParam parameters
    );

    /**
     * Assign product to category
     */
    @WebResult(name = "catalogCategoryAssignProductResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogCategoryAssignProductResponseParam catalogCategoryAssignProduct(
        @WebParam(partName = "parameters", name = "catalogCategoryAssignProductRequestParam", targetNamespace = "urn:Magento")
        CatalogCategoryAssignProductRequestParam parameters
    );

    /**
     * Remove gift card account
     */
    @WebResult(name = "giftcardAccountUpdateResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public GiftcardAccountUpdateResponseParam giftcardAccountUpdate(
        @WebParam(partName = "parameters", name = "giftcardAccountUpdateRequestParam", targetNamespace = "urn:Magento")
        GiftcardAccountUpdateRequestParam parameters
    );

    /**
     * Retrieve attribute options
     */
    @WebResult(name = "catalogProductAttributeOptionsResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductAttributeOptionsResponseParam catalogProductAttributeOptions(
        @WebParam(partName = "parameters", name = "catalogProductAttributeOptionsRequestParam", targetNamespace = "urn:Magento")
        CatalogProductAttributeOptionsRequestParam parameters
    );

    /**
     * List of countries
     */
    @WebResult(name = "directoryCountryListResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public DirectoryCountryListResponseParam directoryCountryList(
        @WebParam(partName = "parameters", name = "directoryCountryListRequestParam", targetNamespace = "urn:Magento")
        DirectoryCountryListRequestParam parameters
    );

    /**
     * Cancel creditmemo
     */
    @WebResult(name = "salesOrderCreditmemoCancelResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public SalesOrderCreditmemoCancelResponseParam salesOrderCreditmemoCancel(
        @WebParam(partName = "parameters", name = "salesOrderCreditmemoCancelRequestParam", targetNamespace = "urn:Magento")
        SalesOrderCreditmemoCancelRequestParam parameters
    );

    /**
     * List of global faults
     */
    @WebResult(name = "globalFaultsResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public GlobalFaultsResponseParam globalFaults(
        @WebParam(partName = "parameters", name = "globalFaultsParam", targetNamespace = "urn:Magento")
        GlobalFaultsParam parameters
    );

    /**
     * Set shipping method
     */
    @WebResult(name = "shoppingCartShippingMethodResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public ShoppingCartShippingMethodResponseParam shoppingCartShippingMethod(
        @WebParam(partName = "parameters", name = "shoppingCartShippingMethodRequestParam", targetNamespace = "urn:Magento")
        ShoppingCartShippingMethodRequestParam parameters
    );

    /**
     * Update product(s) quantities in shopping cart
     */
    @WebResult(name = "shoppingCartProductUpdateResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public ShoppingCartProductUpdateResponseParam shoppingCartProductUpdate(
        @WebParam(partName = "parameters", name = "shoppingCartProductUpdateRequestParam", targetNamespace = "urn:Magento")
        ShoppingCartProductUpdateRequestParam parameters
    );

    /**
     * Create customer address
     */
    @WebResult(name = "customerAddressCreateResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CustomerAddressCreateResponseParam customerAddressCreate(
        @WebParam(partName = "parameters", name = "customerAddressCreateRequestParam", targetNamespace = "urn:Magento")
        CustomerAddressCreateRequestParam parameters
    );

    /**
     * Retrieve gift card data
     */
    @WebResult(name = "giftcardCustomerInfoResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public GiftcardCustomerInfoResponseParam giftcardCustomerInfo(
        @WebParam(partName = "parameters", name = "giftcardCustomerInfoRequestParam", targetNamespace = "urn:Magento")
        GiftcardCustomerInfoRequestParam parameters
    );

    /**
     * Update product link
     */
    @WebResult(name = "catalogProductLinkUpdateResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductLinkUpdateResponseParam catalogProductLinkUpdate(
        @WebParam(partName = "parameters", name = "catalogProductLinkUpdateRequestParam", targetNamespace = "urn:Magento")
        CatalogProductLinkUpdateRequestParam parameters
    );

    /**
     * Remove gift card account
     */
    @WebResult(name = "giftcardAccountRemoveResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public GiftcardAccountRemoveResponseParam giftcardAccountRemove(
        @WebParam(partName = "parameters", name = "giftcardAccountRemoveRequestParam", targetNamespace = "urn:Magento")
        GiftcardAccountRemoveRequestParam parameters
    );

    /**
     * Refresh catalog
     */
    @WebResult(name = "saasRefreshCatalogResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public SaasRefreshCatalogResponseParam saasRefreshCatalog(
        @WebParam(partName = "parameters", name = "saasRefreshCatalogRequestParam", targetNamespace = "urn:Magento")
        SaasRefreshCatalogRequestParam parameters
    );

    /**
     * Create shopping cart
     */
    @WebResult(name = "shoppingCartCreateResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public ShoppingCartCreateResponseParam shoppingCartCreate(
        @WebParam(partName = "parameters", name = "shoppingCartCreateRequestParam", targetNamespace = "urn:Magento")
        ShoppingCartCreateRequestParam parameters
    );

    /**
     * Retrieve stock data by product ids
     */
    @WebResult(name = "catalogInventoryStockItemListResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogInventoryStockItemListResponseParam catalogInventoryStockItemList(
        @WebParam(partName = "parameters", name = "catalogInventoryStockItemListRequestParam", targetNamespace = "urn:Magento")
        CatalogInventoryStockItemListRequestParam parameters
    );

    /**
     * Multiple calls of resource functionality
     */
    @WebResult(name = "multiCallResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public MultiCallResponseParam multiCall(
        @WebParam(partName = "parameters", name = "multiCallParam", targetNamespace = "urn:Magento")
        MultiCallParam parameters
    );

    /**
     * Retrieve customer data
     */
    @WebResult(name = "customerCustomerInfoResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CustomerCustomerInfoResponseParam customerCustomerInfo(
        @WebParam(partName = "parameters", name = "customerCustomerInfoRequestParam", targetNamespace = "urn:Magento")
        CustomerCustomerInfoRequestParam parameters
    );

    /**
     * Update customer address data
     */
    @WebResult(name = "customerAddressUpdateResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CustomerAddressUpdateResponseParam customerAddressUpdate(
        @WebParam(partName = "parameters", name = "customerAddressUpdateRequestParam", targetNamespace = "urn:Magento")
        CustomerAddressUpdateRequestParam parameters
    );

    /**
     * Retrieve linked products
     */
    @WebResult(name = "catalogProductLinkListResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductLinkListResponseParam catalogProductLinkList(
        @WebParam(partName = "parameters", name = "catalogProductLinkListRequestParam", targetNamespace = "urn:Magento")
        CatalogProductLinkListRequestParam parameters
    );

    /**
     * Retrieve customer store credit balance information
     */
    @WebResult(name = "enterpriseCustomerbalanceBalanceResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public EnterpriseCustomerbalanceBalanceResponseParam enterpriseCustomerbalanceBalance(
        @WebParam(partName = "parameters", name = "enterpriseCustomerbalanceBalanceRequestParam", targetNamespace = "urn:Magento")
        EnterpriseCustomerbalanceBalanceRequestParam parameters
    );

    /**
     * Retrieve order information
     */
    @WebResult(name = "salesOrderInfoResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public SalesOrderInfoResponseParam salesOrderInfo(
        @WebParam(partName = "parameters", name = "salesOrderInfoRequestParam", targetNamespace = "urn:Magento")
        SalesOrderInfoRequestParam parameters
    );

    /**
     * Update product stock data
     */
    @WebResult(name = "catalogInventoryStockItemUpdateResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogInventoryStockItemUpdateResponseParam catalogInventoryStockItemUpdate(
        @WebParam(partName = "parameters", name = "catalogInventoryStockItemUpdateRequestParam", targetNamespace = "urn:Magento")
        CatalogInventoryStockItemUpdateRequestParam parameters
    );

    /**
     * Redeem gift card amount
     */
    @WebResult(name = "shoppingCartGiftcardAddResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public ShoppingCartGiftcardAddResponseParam shoppingCartGiftcardAdd(
        @WebParam(partName = "parameters", name = "shoppingCartGiftcardAddRequestParam", targetNamespace = "urn:Magento")
        ShoppingCartGiftcardAddRequestParam parameters
    );

    /**
     * Retrieve creditmemo information
     */
    @WebResult(name = "salesOrderCreditmemoInfoResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public SalesOrderCreditmemoInfoResponseParam salesOrderCreditmemoInfo(
        @WebParam(partName = "parameters", name = "salesOrderCreditmemoInfoRequestParam", targetNamespace = "urn:Magento")
        SalesOrderCreditmemoInfoRequestParam parameters
    );

    /**
     * List of stores
     */
    @WebResult(name = "storeListResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public StoreListResponseParam storeList(
        @WebParam(partName = "parameters", name = "storeListRequestParam", targetNamespace = "urn:Magento")
        StoreListRequestParam parameters
    );

    /**
     * Retrieve customer addresses
     */
    @WebResult(name = "customerAddressListResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CustomerAddressListResponseParam customerAddressList(
        @WebParam(partName = "parameters", name = "customerAddressListRequestParam", targetNamespace = "urn:Magento")
        CustomerAddressListRequestParam parameters
    );

    /**
     * Update category
     */
    @WebResult(name = "catalogCategoryUpdateResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogCategoryUpdateResponseParam catalogCategoryUpdate(
        @WebParam(partName = "parameters", name = "catalogCategoryUpdateRequestParam", targetNamespace = "urn:Magento")
        CatalogCategoryUpdateRequestParam parameters
    );

    /**
     * Retrieve customer groups
     */
    @WebResult(name = "customerGroupListResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CustomerGroupListResponseParam customerGroupList(
        @WebParam(partName = "parameters", name = "customerGroupListRequestParam", targetNamespace = "urn:Magento")
        CustomerGroupListRequestParam parameters
    );

    /**
     * Remove product image
     */
    @WebResult(name = "catalogProductAttributeMediaRemoveResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductAttributeMediaRemoveResponseParam catalogProductAttributeMediaRemove(
        @WebParam(partName = "parameters", name = "catalogProductAttributeMediaRemoveRequestParam", targetNamespace = "urn:Magento")
        CatalogProductAttributeMediaRemoveRequestParam parameters
    );

    /**
     * Login user and retrive session id
     */
    @WebResult(name = "loginResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public LoginResponseParam login(
        @WebParam(partName = "parameters", name = "loginParam", targetNamespace = "urn:Magento")
        LoginParam parameters
    );

    /**
     * Start web service session
     */
    @WebResult(name = "startSessionResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public StartSessionResponseParam startSession();

    /**
     * Upload new product image
     */
    @WebResult(name = "catalogProductAttributeMediaCreateResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductAttributeMediaCreateResponseParam catalogProductAttributeMediaCreate(
        @WebParam(partName = "parameters", name = "catalogProductAttributeMediaCreateRequestParam", targetNamespace = "urn:Magento")
        CatalogProductAttributeMediaCreateRequestParam parameters
    );

    /**
     * Delete product
     */
    @WebResult(name = "catalogProductDeleteResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductDeleteResponseParam catalogProductDelete(
        @WebParam(partName = "parameters", name = "catalogProductDeleteRequestParam", targetNamespace = "urn:Magento")
        CatalogProductDeleteRequestParam parameters
    );

    /**
     * Redeem gift card amount
     */
    @WebResult(name = "shoppingCartGiftcardListResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public ShoppingCartGiftcardListResponseParam shoppingCartGiftcardList(
        @WebParam(partName = "parameters", name = "shoppingCartGiftcardListRequestParam", targetNamespace = "urn:Magento")
        ShoppingCartGiftcardListRequestParam parameters
    );

    /**
     * Set_Get current store view
     */
    @WebResult(name = "catalogCategoryCurrentStoreResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogCategoryCurrentStoreResponseParam catalogCategoryCurrentStore(
        @WebParam(partName = "parameters", name = "catalogCategoryCurrentStoreRequestParam", targetNamespace = "urn:Magento")
        CatalogCategoryCurrentStoreRequestParam parameters
    );

    /**
     * Set customer for shopping cart
     */
    @WebResult(name = "shoppingCartCustomerSetResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public ShoppingCartCustomerSetResponseParam shoppingCartCustomerSet(
        @WebParam(partName = "parameters", name = "shoppingCartCustomerSetRequestParam", targetNamespace = "urn:Magento")
        ShoppingCartCustomerSetRequestParam parameters
    );

    /**
     * Create new product and return product id
     */
    @WebResult(name = "catalogProductCreateResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductCreateResponseParam catalogProductCreate(
        @WebParam(partName = "parameters", name = "catalogProductCreateRequestParam", targetNamespace = "urn:Magento")
        CatalogProductCreateRequestParam parameters
    );

    /**
     * Get product special price data
     */
    @WebResult(name = "catalogProductGetSpecialPriceResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductGetSpecialPriceResponseParam catalogProductGetSpecialPrice(
        @WebParam(partName = "parameters", name = "catalogProductGetSpecialPriceRequestParam", targetNamespace = "urn:Magento")
        CatalogProductGetSpecialPriceRequestParam parameters
    );

    /**
     * Move category in tree
     */
    @WebResult(name = "catalogCategoryMoveResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogCategoryMoveResponseParam catalogCategoryMove(
        @WebParam(partName = "parameters", name = "catalogCategoryMoveRequestParam", targetNamespace = "urn:Magento")
        CatalogCategoryMoveRequestParam parameters
    );

    /**
     * Hold order
     */
    @WebResult(name = "salesOrderHoldResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public SalesOrderHoldResponseParam salesOrderHold(
        @WebParam(partName = "parameters", name = "salesOrderHoldRequestParam", targetNamespace = "urn:Magento")
        SalesOrderHoldRequestParam parameters
    );

    /**
     * Delete customer
     */
    @WebResult(name = "customerCustomerDeleteResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CustomerCustomerDeleteResponseParam customerCustomerDelete(
        @WebParam(partName = "parameters", name = "customerCustomerDeleteRequestParam", targetNamespace = "urn:Magento")
        CustomerCustomerDeleteRequestParam parameters
    );

    /**
     * Retrieve list of shipments by filters
     */
    @WebResult(name = "salesOrderShipmentListResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public SalesOrderShipmentListResponseParam salesOrderShipmentList(
        @WebParam(partName = "parameters", name = "salesOrderShipmentListRequestParam", targetNamespace = "urn:Magento")
        SalesOrderShipmentListRequestParam parameters
    );

    /**
     * Redeem gift card amount
     */
    @WebResult(name = "giftcardCustomerRedeemResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public GiftcardCustomerRedeemResponseParam giftcardCustomerRedeem(
        @WebParam(partName = "parameters", name = "giftcardCustomerRedeemRequestParam", targetNamespace = "urn:Magento")
        GiftcardCustomerRedeemRequestParam parameters
    );

    /**
     * End web service session
     */
    @WebResult(name = "endSessionResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public EndSessionResponseParam endSession(
        @WebParam(partName = "parameters", name = "endSessionParam", targetNamespace = "urn:Magento")
        EndSessionParam parameters
    );

    /**
     * Create new creditmemo for order
     */
    @WebResult(name = "salesOrderCreditmemoCreateResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public SalesOrderCreditmemoCreateResponseParam salesOrderCreditmemoCreate(
        @WebParam(partName = "parameters", name = "salesOrderCreditmemoCreateRequestParam", targetNamespace = "urn:Magento")
        SalesOrderCreditmemoCreateRequestParam parameters
    );

    /**
     * Add comment to order
     */
    @WebResult(name = "salesOrderAddCommentResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public SalesOrderAddCommentResponseParam salesOrderAddComment(
        @WebParam(partName = "parameters", name = "salesOrderAddCommentRequestParam", targetNamespace = "urn:Magento")
        SalesOrderAddCommentRequestParam parameters
    );

    /**
     * Remove gift card account
     */
    @WebResult(name = "giftcardAccountListResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public GiftcardAccountListResponseParam giftcardAccountList(
        @WebParam(partName = "parameters", name = "giftcardAccountListRequestParam", targetNamespace = "urn:Magento")
        GiftcardAccountListRequestParam parameters
    );

    /**
     * Retrieve customer address data
     */
    @WebResult(name = "customerAddressInfoResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CustomerAddressInfoResponseParam customerAddressInfo(
        @WebParam(partName = "parameters", name = "customerAddressInfoRequestParam", targetNamespace = "urn:Magento")
        CustomerAddressInfoRequestParam parameters
    );

    /**
     * Retrieve product image data
     */
    @WebResult(name = "catalogProductAttributeMediaInfoResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductAttributeMediaInfoResponseParam catalogProductAttributeMediaInfo(
        @WebParam(partName = "parameters", name = "catalogProductAttributeMediaInfoRequestParam", targetNamespace = "urn:Magento")
        CatalogProductAttributeMediaInfoRequestParam parameters
    );

    /**
     * Add new comment to creditmemo
     */
    @WebResult(name = "salesOrderCreditmemoAddCommentResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public SalesOrderCreditmemoAddCommentResponseParam salesOrderCreditmemoAddComment(
        @WebParam(partName = "parameters", name = "salesOrderCreditmemoAddCommentRequestParam", targetNamespace = "urn:Magento")
        SalesOrderCreditmemoAddCommentRequestParam parameters
    );

    /**
     * Remove product(s) from shopping cart
     */
    @WebResult(name = "shoppingCartProductRemoveResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public ShoppingCartProductRemoveResponseParam shoppingCartProductRemove(
        @WebParam(partName = "parameters", name = "shoppingCartProductRemoveRequestParam", targetNamespace = "urn:Magento")
        ShoppingCartProductRemoveRequestParam parameters
    );

    /**
     * Update product
     */
    @WebResult(name = "catalogProductUpdateResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductUpdateResponseParam catalogProductUpdate(
        @WebParam(partName = "parameters", name = "catalogProductUpdateRequestParam", targetNamespace = "urn:Magento")
        CatalogProductUpdateRequestParam parameters
    );

    /**
     * Create gift card account
     */
    @WebResult(name = "giftcardAccountCreateResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public GiftcardAccountCreateResponseParam giftcardAccountCreate(
        @WebParam(partName = "parameters", name = "giftcardAccountCreateRequestParam", targetNamespace = "urn:Magento")
        GiftcardAccountCreateRequestParam parameters
    );

    /**
     * Retrieve list of assigned products
     */
    @WebResult(name = "catalogCategoryAssignedProductsResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogCategoryAssignedProductsResponseParam catalogCategoryAssignedProducts(
        @WebParam(partName = "parameters", name = "catalogCategoryAssignedProductsRequestParam", targetNamespace = "urn:Magento")
        CatalogCategoryAssignedProductsRequestParam parameters
    );

    /**
     * Retrieve product attribute sets
     */
    @WebResult(name = "catalogProductAttributeSetListResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductAttributeSetListResponseParam catalogProductAttributeSetList(
        @WebParam(partName = "parameters", name = "catalogProductAttributeSetListRequestParam", targetNamespace = "urn:Magento")
        CatalogProductAttributeSetListRequestParam parameters
    );

    /**
     * Retrieve hierarchical tree of categories.
     */
    @WebResult(name = "catalogCategoryLevelResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogCategoryLevelResponseParam catalogCategoryLevel(
        @WebParam(partName = "parameters", name = "catalogCategoryLevelRequestParam", targetNamespace = "urn:Magento")
        CatalogCategoryLevelRequestParam parameters
    );

    /**
     * Update customer data
     */
    @WebResult(name = "customerCustomerUpdateResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CustomerCustomerUpdateResponseParam customerCustomerUpdate(
        @WebParam(partName = "parameters", name = "customerCustomerUpdateRequestParam", targetNamespace = "urn:Magento")
        CustomerCustomerUpdateRequestParam parameters
    );

    /**
     * Update product tier prices
     */
    @WebResult(name = "catalogProductAttributeTierPriceUpdateResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductAttributeTierPriceUpdateResponseParam catalogProductAttributeTierPriceUpdate(
        @WebParam(partName = "parameters", name = "catalogProductAttributeTierPriceUpdateRequestParam", targetNamespace = "urn:Magento")
        CatalogProductAttributeTierPriceUpdateRequestParam parameters
    );

    /**
     * Retrieve product tier prices
     */
    @WebResult(name = "catalogProductAttributeTierPriceInfoResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductAttributeTierPriceInfoResponseParam catalogProductAttributeTierPriceInfo(
        @WebParam(partName = "parameters", name = "catalogProductAttributeTierPriceInfoRequestParam", targetNamespace = "urn:Magento")
        CatalogProductAttributeTierPriceInfoRequestParam parameters
    );

    /**
     * Retrieve customer store credit history information
     */
    @WebResult(name = "enterpriseCustomerbalanceHistoryResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public EnterpriseCustomerbalanceHistoryResponseParam enterpriseCustomerbalanceHistory(
        @WebParam(partName = "parameters", name = "enterpriseCustomerbalanceHistoryRequestParam", targetNamespace = "urn:Magento")
        EnterpriseCustomerbalanceHistoryRequestParam parameters
    );

    /**
     * List of regions in specified country
     */
    @WebResult(name = "directoryRegionListResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public DirectoryRegionListResponseParam directoryRegionList(
        @WebParam(partName = "parameters", name = "directoryRegionListRequestParam", targetNamespace = "urn:Magento")
        DirectoryRegionListRequestParam parameters
    );

    /**
     * Retrieve product link types
     */
    @WebResult(name = "catalogProductLinkTypesResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductLinkTypesResponseParam catalogProductLinkTypes(
        @WebParam(partName = "parameters", name = "catalogProductLinkTypesRequestParam", targetNamespace = "urn:Magento")
        CatalogProductLinkTypesRequestParam parameters
    );

    /**
     * Remove product link
     */
    @WebResult(name = "catalogProductLinkRemoveResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductLinkRemoveResponseParam catalogProductLinkRemove(
        @WebParam(partName = "parameters", name = "catalogProductLinkRemoveRequestParam", targetNamespace = "urn:Magento")
        CatalogProductLinkRemoveRequestParam parameters
    );

    /**
     * Remove amount from shopping cart (quote) and increase customer store credit
     */
    @WebResult(name = "shoppingCartCustomerbalanceRemoveAmountResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public ShoppingCartCustomerbalanceRemoveAmountResponseParam shoppingCartCustomerbalanceRemoveAmount(
        @WebParam(partName = "parameters", name = "shoppingCartCustomerbalanceRemoveAmountRequestParam", targetNamespace = "urn:Magento")
        ShoppingCartCustomerbalanceRemoveAmountRequestParam parameters
    );

    /**
     * Cancel invoice
     */
    @WebResult(name = "salesOrderInvoiceCancelResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public SalesOrderInvoiceCancelResponseParam salesOrderInvoiceCancel(
        @WebParam(partName = "parameters", name = "salesOrderInvoiceCancelRequestParam", targetNamespace = "urn:Magento")
        SalesOrderInvoiceCancelRequestParam parameters
    );

    /**
     * Multi update product stock data
     */
    @WebResult(name = "catalogProductMultiUpdateResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductMultiUpdateResponseParam catalogProductMultiUpdate(
        @WebParam(partName = "parameters", name = "catalogProductMultiUpdateRequestParam", targetNamespace = "urn:Magento")
        CatalogProductMultiUpdateRequestParam parameters
    );

    /**
     * Remove coupon code from shopping cart
     */
    @WebResult(name = "shoppingCartCouponRemoveResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public ShoppingCartCouponRemoveResponseParam shoppingCartCouponRemove(
        @WebParam(partName = "parameters", name = "shoppingCartCouponRemoveRequestParam", targetNamespace = "urn:Magento")
        ShoppingCartCouponRemoveRequestParam parameters
    );

    /**
     * Retrieve product image list
     */
    @WebResult(name = "catalogProductAttributeMediaListResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductAttributeMediaListResponseParam catalogProductAttributeMediaList(
        @WebParam(partName = "parameters", name = "catalogProductAttributeMediaListRequestParam", targetNamespace = "urn:Magento")
        CatalogProductAttributeMediaListRequestParam parameters
    );

    /**
     * Get list of available payment methods
     */
    @WebResult(name = "shoppingCartPaymentListResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public ShoppingCartPaymentListResponseParam shoppingCartPaymentList(
        @WebParam(partName = "parameters", name = "shoppingCartPaymentListRequestParam", targetNamespace = "urn:Magento")
        ShoppingCartPaymentListRequestParam parameters
    );

    /**
     * Retrieve product tag info
     */
    @WebResult(name = "catalogProductTagInfoResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductTagInfoResponseParam catalogProductTagInfo(
        @WebParam(partName = "parameters", name = "catalogProductTagInfoRequestParam", targetNamespace = "urn:Magento")
        CatalogProductTagInfoRequestParam parameters
    );

    /**
     * Retrieve list of tags by product
     */
    @WebResult(name = "catalogProductTagListResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductTagListResponseParam catalogProductTagList(
        @WebParam(partName = "parameters", name = "catalogProductTagListRequestParam", targetNamespace = "urn:Magento")
        CatalogProductTagListRequestParam parameters
    );

    /**
     * Retrieve product link type attributes
     */
    @WebResult(name = "catalogProductLinkAttributesResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductLinkAttributesResponseParam catalogProductLinkAttributes(
        @WebParam(partName = "parameters", name = "catalogProductLinkAttributesRequestParam", targetNamespace = "urn:Magento")
        CatalogProductLinkAttributesRequestParam parameters
    );

    /**
     * Retrieve hierarchical tree of categories.
     */
    @WebResult(name = "catalogCategoryInfoResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogCategoryInfoResponseParam catalogCategoryInfo(
        @WebParam(partName = "parameters", name = "catalogCategoryInfoRequestParam", targetNamespace = "urn:Magento")
        CatalogCategoryInfoRequestParam parameters
    );

    /**
     * Call api functionality
     */
    @WebResult(name = "callResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CallResponseParam call(
        @WebParam(partName = "parameters", name = "callParam", targetNamespace = "urn:Magento")
        CallParam parameters
    );

    /**
     * Add product(s) to shopping cart
     */
    @WebResult(name = "shoppingCartProductAddResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public ShoppingCartProductAddResponseParam shoppingCartProductAdd(
        @WebParam(partName = "parameters", name = "shoppingCartProductAddRequestParam", targetNamespace = "urn:Magento")
        ShoppingCartProductAddRequestParam parameters
    );

    /**
     * Create new invoice for order
     */
    @WebResult(name = "salesOrderInvoiceCreateResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public SalesOrderInvoiceCreateResponseParam salesOrderInvoiceCreate(
        @WebParam(partName = "parameters", name = "salesOrderInvoiceCreateRequestParam", targetNamespace = "urn:Magento")
        SalesOrderInvoiceCreateRequestParam parameters
    );

    /**
     * Update product special price
     */
    @WebResult(name = "catalogProductSetSpecialPriceResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductSetSpecialPriceResponseParam catalogProductSetSpecialPrice(
        @WebParam(partName = "parameters", name = "catalogProductSetSpecialPriceRequestParam", targetNamespace = "urn:Magento")
        CatalogProductSetSpecialPriceRequestParam parameters
    );

    /**
     * Retrieve product
     */
    @WebResult(name = "catalogProductInfoResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductInfoResponseParam catalogProductInfo(
        @WebParam(partName = "parameters", name = "catalogProductInfoRequestParam", targetNamespace = "urn:Magento")
        CatalogProductInfoRequestParam parameters
    );

    /**
     * Send shipment info
     */
    @WebResult(name = "salesOrderShipmentSendInfoResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public SalesOrderShipmentSendInfoResponseParam salesOrderShipmentSendInfo(
        @WebParam(partName = "parameters", name = "salesOrderShipmentSendInfoRequestParam", targetNamespace = "urn:Magento")
        SalesOrderShipmentSendInfoRequestParam parameters
    );

    /**
     * Retrieve list of invoices by filters
     */
    @WebResult(name = "salesOrderInvoiceListResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public SalesOrderInvoiceListResponseParam salesOrderInvoiceList(
        @WebParam(partName = "parameters", name = "salesOrderInvoiceListRequestParam", targetNamespace = "urn:Magento")
        SalesOrderInvoiceListRequestParam parameters
    );

    /**
     * Get list of products in shopping cart
     */
    @WebResult(name = "shoppingCartProductListResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public ShoppingCartProductListResponseParam shoppingCartProductList(
        @WebParam(partName = "parameters", name = "shoppingCartProductListRequestParam", targetNamespace = "urn:Magento")
        ShoppingCartProductListRequestParam parameters
    );

    /**
     * Set/Get current store view
     */
    @WebResult(name = "catalogProductCurrentStoreResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductCurrentStoreResponseParam catalogProductCurrentStore(
        @WebParam(partName = "parameters", name = "catalogProductCurrentStoreRequestParam", targetNamespace = "urn:Magento")
        CatalogProductCurrentStoreRequestParam parameters
    );

    /**
     * Setting a gift messages to the quote item
     */
    @WebResult(name = "giftMessageForQuoteItemResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public GiftMessageForQuoteItemResponseParam giftMessageSetForQuoteItem(
        @WebParam(partName = "parameters", name = "giftMessageForQuoteItemRequestParam", targetNamespace = "urn:Magento")
        GiftMessageForQuoteItemRequestParam parameters
    );

    /**
     * Add tag(s) to product
     */
    @WebResult(name = "catalogProductTagAddResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductTagAddResponseParam catalogProductTagAdd(
        @WebParam(partName = "parameters", name = "catalogProductTagAddRequestParam", targetNamespace = "urn:Magento")
        CatalogProductTagAddRequestParam parameters
    );

    /**
     * Void invoice
     */
    @WebResult(name = "salesOrderInvoiceVoidResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public SalesOrderInvoiceVoidResponseParam salesOrderInvoiceVoid(
        @WebParam(partName = "parameters", name = "salesOrderInvoiceVoidRequestParam", targetNamespace = "urn:Magento")
        SalesOrderInvoiceVoidRequestParam parameters
    );

    /**
     * Unhold order
     */
    @WebResult(name = "salesOrderUnholdResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public SalesOrderUnholdResponseParam salesOrderUnhold(
        @WebParam(partName = "parameters", name = "salesOrderUnholdRequestParam", targetNamespace = "urn:Magento")
        SalesOrderUnholdRequestParam parameters
    );

    /**
     * List of available resources
     */
    @WebResult(name = "resourcesResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public ResourcesResponseParam resources(
        @WebParam(partName = "parameters", name = "resourcesRequestParam", targetNamespace = "urn:Magento")
        ResourcesRequestParam parameters
    );

    /**
     * Get list of available shipping methods
     */
    @WebResult(name = "shoppingCartShippingListResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public ShoppingCartShippingListResponseParam shoppingCartShippingList(
        @WebParam(partName = "parameters", name = "shoppingCartShippingListRequestParam", targetNamespace = "urn:Magento")
        ShoppingCartShippingListRequestParam parameters
    );

    /**
     * Add new comment to shipment
     */
    @WebResult(name = "salesOrderShipmentAddCommentResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public SalesOrderShipmentAddCommentResponseParam salesOrderShipmentAddComment(
        @WebParam(partName = "parameters", name = "salesOrderShipmentAddCommentRequestParam", targetNamespace = "urn:Magento")
        SalesOrderShipmentAddCommentRequestParam parameters
    );

    /**
     * Get terms and conditions
     */
    @WebResult(name = "shoppingCartLicenseResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public ShoppingCartLicenseResponseParam shoppingCartLicense(
        @WebParam(partName = "parameters", name = "shoppingCartLicenseRequestParam", targetNamespace = "urn:Magento")
        ShoppingCartLicenseRequestParam parameters
    );

    /**
     * Add coupon code for shopping cart
     */
    @WebResult(name = "shoppingCartCouponAddResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public ShoppingCartCouponAddResponseParam shoppingCartCouponAdd(
        @WebParam(partName = "parameters", name = "shoppingCartCouponAddRequestParam", targetNamespace = "urn:Magento")
        ShoppingCartCouponAddRequestParam parameters
    );

    /**
     * Set payment method
     */
    @WebResult(name = "shoppingCartPaymentMethodResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public ShoppingCartPaymentMethodResponseParam shoppingCartPaymentMethod(
        @WebParam(partName = "parameters", name = "shoppingCartPaymentMethodRequestParam", targetNamespace = "urn:Magento")
        ShoppingCartPaymentMethodRequestParam parameters
    );

    /**
     * Update product tag
     */
    @WebResult(name = "catalogProductTagUpdateResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductTagUpdateResponseParam catalogProductTagUpdate(
        @WebParam(partName = "parameters", name = "catalogProductTagUpdateRequestParam", targetNamespace = "urn:Magento")
        CatalogProductTagUpdateRequestParam parameters
    );

    /**
     * Add new comment to shipment
     */
    @WebResult(name = "salesOrderInvoiceAddCommentResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public SalesOrderInvoiceAddCommentResponseParam salesOrderInvoiceAddComment(
        @WebParam(partName = "parameters", name = "salesOrderInvoiceAddCommentRequestParam", targetNamespace = "urn:Magento")
        SalesOrderInvoiceAddCommentRequestParam parameters
    );

    /**
     * Remove gift card account
     */
    @WebResult(name = "giftcardAccountInfoResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public GiftcardAccountInfoResponseParam giftcardAccountInfo(
        @WebParam(partName = "parameters", name = "giftcardAccountInfoRequestParam", targetNamespace = "urn:Magento")
        GiftcardAccountInfoRequestParam parameters
    );

    /**
     * Set customer's addresses in shopping cart
     */
    @WebResult(name = "shoppingCartCustomerAddressesResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public ShoppingCartCustomerAddressesResponseParam shoppingCartCustomerAddresses(
        @WebParam(partName = "parameters", name = "shoppingCartCustomerAddressesRequestParam", targetNamespace = "urn:Magento")
        ShoppingCartCustomerAddressesRequestParam parameters
    );

    /**
     * Set/Get current store view
     */
    @WebResult(name = "catalogProductAttributeMediaCurrentStoreResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductAttributeMediaCurrentStoreResponseParam catalogProductAttributeMediaCurrentStore(
        @WebParam(partName = "parameters", name = "catalogProductAttributeMediaCurrentStoreRequestParam", targetNamespace = "urn:Magento")
        CatalogProductAttributeMediaCurrentStoreRequestParam parameters
    );

    /**
     * Create customer
     */
    @WebResult(name = "customerCustomerCreateResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CustomerCustomerCreateResponseParam customerCustomerCreate(
        @WebParam(partName = "parameters", name = "customerCustomerCreateRequestParam", targetNamespace = "urn:Magento")
        CustomerCustomerCreateRequestParam parameters
    );

    /**
     * Setting a gift messages to the quote items by products
     */
    @WebResult(name = "giftMessageForQuoteProductResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public GiftMessageForQuoteProductResponseParam giftMessageSetForQuoteProduct(
        @WebParam(partName = "parameters", name = "giftMessageForQuoteProductRequestParam", targetNamespace = "urn:Magento")
        GiftMessageForQuoteProductRequestParam parameters
    );

    /**
     * Move product(s) to customer quote
     */
    @WebResult(name = "shoppingCartProductMoveToCustomerQuoteResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public ShoppingCartProductMoveToCustomerQuoteResponseParam shoppingCartProductMoveToCustomerQuote(
        @WebParam(partName = "parameters", name = "shoppingCartProductMoveToCustomerQuoteRequestParam", targetNamespace = "urn:Magento")
        ShoppingCartProductMoveToCustomerQuoteRequestParam parameters
    );

    /**
     * Add new tracking number
     */
    @WebResult(name = "salesOrderShipmentAddTrackResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public SalesOrderShipmentAddTrackResponseParam salesOrderShipmentAddTrack(
        @WebParam(partName = "parameters", name = "salesOrderShipmentAddTrackRequestParam", targetNamespace = "urn:Magento")
        SalesOrderShipmentAddTrackRequestParam parameters
    );

    /**
     * Capture invoice
     */
    @WebResult(name = "salesOrderInvoiceCaptureResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public SalesOrderInvoiceCaptureResponseParam salesOrderInvoiceCapture(
        @WebParam(partName = "parameters", name = "salesOrderInvoiceCaptureRequestParam", targetNamespace = "urn:Magento")
        SalesOrderInvoiceCaptureRequestParam parameters
    );
}
